workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  my-source:
    inputs:
      - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/main/plex-media-server-spec-dereferenced.yaml
targets:
  plexpy:
    target: python
    source: my-source
    codeSamples:
      output: codeSamples.yaml
    publish:
      pypi:
        token: $PYPI_TOKEN
