workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api:main
targets:
    plexpy:
        target: python
        source: my-source
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-python-plexpy
